# -*- coding: utf-8 -*-
"""SENAC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sltreDhmOLRo_NVTX8WlGSzsGq00gy_g
"""

try:
    temperatura = float(input("Digite a temperatura em graus Celsius: "))

    if temperatura < 0:
        print("Está muito frio.")
    elif temperatura <= 20:
        print("Está frio.")
    elif temperatura <= 30:
        print("Está agradável.")
    else:
        print("Está quente.")

except ValueError:
    print("Entrada inválida! Por favor, digite um número válido.")

for x in range(0,20):
  if x % 2 == 0: print(x)

x = int(input("Me diga um numero"))

if x % 2 == 0:
  print("par")
else:
    print("impar")

"""# Nova seção"""

numero = int(input("será que é primo?"))
for x in range(2, numero):
 if numero%x ==0:
  print("O numero não é primo, ele é divisivel por", x)
  break
else:
  print("O numero é primo ele é divisivel por", x)

soma = 0
for i in range(1000):
    if i % 3 == 0 or i % 5 == 0:
        soma += i

print(soma)

teste = int(input("Escreva um numero"))

if teste % 3 == 0 and teste % 5 ==0:
  print("é divisivel por 3")
  print("é divisivel por 5")

lista =  'Quem ler é gay'
print(len(lista))

mercado = ("arroz", "feijão", "batata", "banana", "pão", "queijo", "sabão", "suco", "leite", "farofa")
print(mercado[0], mercado[1])
print(mercado[0][0])

carro = [["Ford", "mustang", "preto", "2007", "Porte esportivo"],
["volkswagen", "GTI", "1993", "Porte Compacto", "branco"],
["Chevrolet", "Camaro", "amarelo", "2010", "Porte Esportivo"],
["Honda", "Civic", "cinza", "2015", "Porte Médio"],
["Honda", "Civic", "cinza", "2015", "Porte Médio"]]
print(carro[0][1], carro[1][1], carro[2][1], carro[3][1], carro[4][1])

frase = ("Ésta muito frio")
for letra in frase:
    print(letra)

frase = "Ésta muito frio"
for letra in  range( 14, -1, -1):
    print(frase[letra])

"""# Nova seção"""

fib = [0, 1]
while fib[-1] <= 1000:

    fib.append(fib[-1]+fib[-2])
fib.pop()
print(fib)

a, b = 0, 1
while a <= 1000:
  print(a)
  a, b = b, a + b

primo = True
lista= [0, 1, 2]
for x in range(3, 101):
  for y in range(2,x):
    if x % y ==0:
     primo = False
     break
  if primo:
    lista.append(x)
  else:
   primo = True
print(lista)

try:
    idade = float(input("Digite a sua idade:"))

    if idade < 0:
        print("bebê")
    elif idade <= 10:
        print("Criança.")
    elif idade <= 19:
        print("adolescente")
    elif idade <= 65:
        print("Idoso")
    else:
        print("Super idoso")

except ValueError:
    print("Entrada inválida! Por favor, digite um número válido.")

import random

answer = random.randint(1, 10)

while 1 > 0:
  adivinhe = int(input("Acerte o número entre 1 e 10:6"))
  if answer == adivinhe:
    print("Você adivinhou!")
    break
  elif answer < adivinhe and adivinhe <= 10:
    print("Esse número é maior que o desejado.")
  elif adivinhe >10:
    print("Esse número não existe na sequência.")
  else:
    print("Esse número é menor que o desejado.")

import random

def jogar_pedra_papel_tesoura():
    opcoes = ['pedra', 'papel', 'tesoura']
    print("Bem-vindo ao Pedra, Papel, Tesoura!")

    while True:
        try:
            escolha_jogador = input("Escolha pedra, papel ou tesoura: ").lower()
            if escolha_jogador not in opcoes:
                raise ValueError("Escolha inválida. Tente novamente.")

            escolha_computador = random.choice(opcoes)
            print(f"O computador escolheu: {escolha_computador}")

            if escolha_jogador == escolha_computador:
                print("Empate!")
            elif (escolha_jogador == 'pedra' and escolha_computador == 'tesoura') or \
                 (escolha_jogador == 'papel' and escolha_computador == 'pedra') or \
                 (escolha_jogador == 'tesoura' and escolha_computador == 'papel'):
                print("Você venceu!")
            else:
                print("Você perdeu!")

            jogar_novamente = input("Deseja jogar novamente? (sim/não): ").strip().lower()
            if jogar_novamente != 'sim':
                print("Obrigado por jogar! Até a próxima.")
                break

        except ValueError as erro:
            print(erro)

if __name__ == "__main__":
    jogar_pedra_papel_tesoura()

idade = int(input("me fale sua idade"))
if  idade  <= 18 and idade <= 60:
  print("você tem idade suficiente pra ser preso")
else:
  print("saia daqui palhaço")

login = input("Me fale seu login: ")
senha = int(input("Digite sua senha: "))

login_sistema = "admin"
senha_sistema = 1234

if login == login_sistema and senha == senha_sistema:
    print("Bem-vindo!")
else:
    print("Login ou senha incorretos.")

number = int(input("Digite o seu número: "))

if number >= 0 and number <= 20:
  print(number)
else:
  print(not number)

idade = int(input("me fale sua idade"))
if idade >= 16:
 print("você ja pode vota")
else:
  print("você não pode votar")
if idade >= 18:
  print("você ja pode dirigir")
else:
  print("você não pode dirigir")

A = input("Digite True ou False para A: ") == "true"
B = input("Digite True ou False para B: ") == "true"
C = input("Digite True ou False para C: ") == "true"
resultado = (A or B) and not C

print("Resultado:", resultado)

palindrome = []

for num in range(10000, 998001):
    if str(num) == str(num)[::-1]:
        palindrome.append(num)

print(max(palindrome))

try:
    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))

    soma = num1 + num2

    print("A soma dos dois números é:", soma)

except ValueError:

    print("Entrada inválida! Por favor, digite um número válido.")

num = int(input("Digite um número: "))
fatorial = 1
for i in range(1, num + 1):
    fatorial *= i
print(f"O fatorial de {num} é {fatorial}")

numero = int(input("será que é primo?"))
for x in range(2, numero):
 if numero%x ==0:
  print("O numero não é primo, ele é divisivel por", x)
  break
else:
  print("O numero é primo ele é divisivel por", x)

x = int(input("Me diga um numero"))

if x % 2 == 0:
  print("par")
else:
    print("impar")

numeros = [10, 45, 2, 89, 33]
maior = max(numeros)
print("O maior número é:", maior)

texto = input("Digite uma palavra ou frase: ")
invertido = texto[::-1]
print("Texto invertido:", invertido)